defaults: &defaults
  docker:
    - image: circleci/node:8.11.3
  environment:
    CC_TEST_REPORTER_ID: 39ff6fab79be04ad2f3f4fe6d57d7665c761a8c0875f5f38c27624ed60ae3a22
  working_directory: ~/repo

version: 2

jobs:
  setup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-
      - run: 
          name: Installing dependencies
          command: npm install --ignore-scripts
      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: Running linter
          command: npm run lint
      - run:
          name: Setting up CodeClimate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Running unit tests
          command: |
            ./cc-test-reporter before-build
            npm run test -- --coverageDirectory "./coverage"
            ./cc-test-reporter after-build --coverage-input-type lcov

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Running build
          command: npm run build  
      - persist_to_workspace:
          root: .
          paths:
            - dist 

  publish-npm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticating user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to NPM
          command: |
            if ! npm publish; then
              echo command returned true
            fi

  cleanup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Removing dev dependencies
          command: rm -rf node_modules
      - run: 
          name: Installing prod dependencies
          command: npm install --production --ignore-scripts
      - persist_to_workspace:
          root: .
          paths:
            - node_modules 

workflows:
  version: 2

  acceptance:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - test:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - setup
      - build:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - setup

  release:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
      - cleanup:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - build
      - build:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - setup
      - test:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - setup
      - publish-npm:
          filters:
            branches:
              only:
                - master
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]$/
          requires:
            - cleanup
            - test
