version: 2

jobs:

  test:
    docker:
      - image: circleci/node:8.9.1
    environment:
        CC_TEST_REPORTER_ID: 39ff6fab79be04ad2f3f4fe6d57d7665c761a8c0875f5f38c27624ed60ae3a22
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Installing dependencies
          command: npm install --ignore-scripts
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running codestyle checks
          command: npm run cs-check
      - run:
          name: Setting up CodeClimate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Running unit tests
          command: |
            ./cc-test-reporter before-build
            npm run test -- --coverageDirectory "./coverage"
            ./cc-test-reporter after-build --coverage-input-type lcov

  build:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Installing dependencies
          command: npm install --ignore-scripts
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running build
          command: npm run build   

  publish-npm:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: Installing dependencies
          command: npm install --ignore-scripts
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Authenticating user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to NPM
          command: npm publish

workflows:
  version: 2

  acceptance:
      jobs:
        - test:
            filters:
              branches:
                ignore: gh-pages
        - build:
            filters:
              branches:
                ignore: gh-pages

  release:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - master
              tags:
                only: /^[0-9]+\.[0-9]+\.[0-9]$/
        - publish-npm:
            filters:
              branches:
                only:
                  - master
              tags:
                only: /^[0-9]+\.[0-9]+\.[0-9]$/
            requires:
              - build
